
name: Test consuming external identity in Django admin application

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 21 * * 0'

jobs:
  docker-compose-keycloak:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        django_version:
          -
          - 4.2
          - 5.1
    steps:
      - uses: actions/checkout@v4
      - run: make build DJANGO_VERSION=${{ matrix.django_version }}
      - run: sudo apt update && sudo apt install -y libwww-mechanize-perl libhttp-cookiejar-perl
      - run: echo '127.0.0.5 www keycloak' | sudo tee -a /etc/hosts
      - run: make run
      - run: make test
      - run: make restart-app
      - run: make test-client-container
      - run: make restart-app
      - run: make test-client-container

